In [3]:
!pip install numpy


  Using cached numpy-2.3.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 8.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.6/12.8 MB 4.0 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.8 MB 4.1 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.8 MB 3.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.8 MB 3.7 MB/s eta 0:00:03
   ------------- -------------------------- 4.5/12.8 MB 3.4 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.8 MB 3.7 MB/s eta 0:00:03
   ------------------ --------------------- 6.0/12.8 MB 3.6 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.8 MB 3.5 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.8 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/12.8 MB 3.3 MB/s eta 0:00:02
   ----------

In [4]:
#create array using numpy
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
#2D Array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size or Number of elements:",arr.size)
print("Data type:",arr.dtype)
print("Item size:", arr.itemsize)



Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size or Number of elements: 6
Data type: int64
Item size: 8


In [15]:
#Numpy Vectroized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])\

#Element Wise Addition
print("Addition:", arr1+arr2)

#Element Wise Subtraction
print("Subtraction", arr1-arr2)

#Element Wise Multiplication
print("Multiplication", arr1*arr2)

#Element Wise Division
print("Division", arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Division [0.1 0.1 0.1 0.1 0.1]


In [16]:
##Universal Function
arr = np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))


#Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [17]:
#Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
arr[0]

array([1, 2, 3, 4])

In [21]:
arr[0][1]

np.int64(2)

In [23]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [25]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [26]:
#Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [27]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [29]:
#Stastical concept -- Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

mean = np.mean(data)
print(mean)
std_dev = np.std(data)
print(std_dev)

#Normalize the data
normalized_data = (data-mean) / std_dev
print("Normalized data:" ,normalized_data)

3.0
1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

#Mean
mean = np.mean(data)
print("Mean", mean)

#Median
median = np.median(data)
print("Median",median)

#Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

#Variance
variance = np.var(data)
print("Variance:",variance)


Mean 5.5
Median 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [34]:
##Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5)
print(data[data>5])
print(data[(data>=5) & (data<=8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
