# Module: NumPy Assignments
## Lesson: NumPy


In [7]:
### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
import numpy as np
arr1 = np.random.randint(1,21,size=(5,5))
print("Original Array")
print(arr1)
arr1[:,2]=1
print("Array1 after Modification")
print(arr1)

arr2 = np.random.randint(1,17,size=(4,4))
print("Printing Original Array")
print(arr2)

np.fill_diagonal(arr2,0)
print(arr2)

Original Array
[[18  7  9 20 14]
 [16 10 20  2 13]
 [ 6 19  5 17 14]
 [ 3  6  1 12 19]
 [ 8  9 11  6 16]]
Array1 after Modification
[[18  7  1 20 14]
 [16 10  1  2 13]
 [ 6 19  1 17 14]
 [ 3  6  1 12 19]
 [ 8  9  1  6 16]]
Printing Original Array
[[ 5  1 10  8]
 [ 9 10 12  1]
 [10  7 12 12]
 [14  5 14  7]]
[[ 0  1 10  8]
 [ 9  0 12  1]
 [10  7  0 12]
 [14  5 14  0]]


In [12]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

arr1 = np.random.randint(1,37,size=(6,6))
print("Original Array")
print(arr1)
print(arr1[3:6,2:5])

arr2 = np.random.randint(1,100,size=(5,5))
print("Original Array")
print(arr2)

borders_element = np.concatenate((
    arr2[0,:],
    arr2[-1,:],
    arr2[1:-1,0],
    arr2[1:-1,-1]
))
print("Border Element",borders_element)

Original Array
[[19  8 18 23 23  9]
 [19  1 26 15 36 28]
 [ 6 10 12 28 14 36]
 [36 31 18 20  8 18]
 [13 11 36 14 26 24]
 [ 3 22 33 15 23 10]]
[[18 20  8]
 [36 14 26]
 [33 15 23]]
Original Array
[[41 46 17 64 52]
 [ 1 88 54 77 99]
 [39 94 19 91 70]
 [ 7 40 33 34 55]
 [59 64 47 72 15]]
Border Element [41 46 17 64 52 59 64 47 72 15  1 39  7 99 70 55]


In [ ]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

arr1 = np.random.randint(1,10,size=(3,4))
arr2 = np.random.randint(1,20,size=(3,4))
print(arr1)
print(arr2)
arr_add = arr1+arr2
print("Addition of Array")
print(arr_add)
arr_sub = arr1-arr2
print("Substraction of Array")
print(arr_sub)
arr_mul = arr1*arr2
print("Multiplication of Array")
print(arr_mul)
arr_div = arr1/arr2
print("Division of Array")
print(arr_div)



[[8 1 7 1]
 [1 3 5 8]
 [3 9 8 8]]
[[18 14 18  4]
 [12 18  4 10]
 [10 19  4  4]]
Addition of Array
[[26 15 25  5]
 [13 21  9 18]
 [13 28 12 12]]
Substraction of Array
[[-10 -13 -11  -3]
 [-11 -15   1  -2]
 [ -7 -10   4   4]]
Multiplication of Array
[[144  14 126   4]
 [ 12  54  20  80]
 [ 30 171  32  32]]
Division of Array
[[0.44444444 0.07142857 0.38888889 0.25      ]
 [0.08333333 0.16666667 1.25       0.8       ]
 [0.3        0.47368421 2.         2.        ]]


In [19]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr  = np.random.randint(1,17,size=(4,4))
print("Original Array")
print(arr)

row_sum = np.sum(arr,axis=1)
print("Row Sum")
print(row_sum)

col_sum = np.sum(arr,axis=0)
print("Column Sum")
print(col_sum)

Original Array
[[15 15  3  4]
 [15  5  3  3]
 [11  7  2 16]
 [12 10  3  8]]
Row Sum
[37 26 36 33]
Column Sum
[53 37 11 31]


In [20]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr = np.random.randint(1,21,size=(5,5))
print("Original Array")

arr_mean = np.mean(arr)
print("Mean", arr_mean)

arr_median = np.median(arr)
print("Median",arr_median)

arr_std = np.std(arr)
print("Standard Deviation",arr_std)

arr_var = np.var(arr)
print("Variance",arr_var)

Original Array
Mean 9.44
Median 9.0
Standard Deviation 5.776365639396453
Variance 33.3664


In [21]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
data = np.random.randint(1,10,size=(3,3))
mean = np.mean(data)
std_dev = np.std(data)
nor = (data-mean)/std_dev
print("Normalization")
print(nor)

Normalization
[[ 0.30316953 -0.78824078 -1.87965109]
 [-0.78824078  1.39457984 -0.24253563]
 [ 1.39457984  0.30316953  0.30316953]]


In [4]:
### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
arr = np.random.randint(1,20,size=(3,3))
print(arr)
vec = np.array([1,2,3])
print(vec)
result = arr+vec
print("Printing Array after Broadcasting")
print(result)


[[19  9 18]
 [ 9 18 16]
 [ 4  4 15]]
[1 2 3]
Printing Array after Broadcasting
[[20 11 21]
 [10 20 19]
 [ 5  6 18]]


In [8]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr = np.random.randint(1,20,size=(4,4))
print(arr)
vec = np.array([1,2,3,4])
result = arr-vec.reshape(4,1)
print(result)

[[10 11  9  1]
 [ 8  5  9 19]
 [10 10 11 16]
 [16 15  2  7]]
[[ 9 10  8  0]
 [ 6  3  7 17]
 [ 7  7  8 13]
 [12 11 -2  3]]


In [11]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

Arr = np.random.randint(1,20,size=(3,3))
print("Original Array")
print(Arr)

det_Arr = np.linalg.det(Arr)
print("Determinant Array")
print(det_Arr)

if det_Arr!=0:
    inv_Arr = np.linalg.inv(Arr)
    print("Inverse Array")
    print(inv_Arr)
else:
    print("Inverse Not Exist")

eigenvalues, eigenvectors = np.linalg.eig(Arr)
print("Eigen Values",eigenvalues)
print("Eigen Vectors",eigenvectors)


Original Array
[[13  4  7]
 [ 5 13  2]
 [12 14  3]]
Determinant Array
-422.99999999999983
Inverse Array
[[-0.02600473 -0.20330969  0.19621749]
 [-0.0212766   0.10638298 -0.0212766 ]
 [ 0.20330969  0.31678487 -0.35224586]]
Eigen Values [23.27949323  7.99362928 -2.27312251]
Eigen Vectors [[-0.61653185 -0.72764314 -0.42066641]
 [-0.42840676  0.67228987  0.01894156]
 [-0.66057257  0.13624169  0.90701763]]


In [14]:
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
arr1 = np.random.randint(1,20,size=(2,3))
print(arr1)
arr2 = np.random.randint(10,20,size=(3,2))
print(arr2)
if arr1.shape[1] == arr2.shape[0]:
    result = np.dot(arr1,arr2)
    print(result)
else:
    print("Multiplication not possible")


[[ 4 16  9]
 [ 1  7 13]]
[[19 18]
 [14 16]
 [17 16]]
[[453 472]
 [338 338]]


In [16]:
### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
arr1 = np.random.randint(1,9,size=(3,3))
print(arr1)
print(arr1.reshape(1,9))
print(arr1.reshape(9,1))


[[4 6 8]
 [8 8 8]
 [1 3 3]]
[[4 6 8 8 8 8 1 3 3]]
[[4]
 [6]
 [8]
 [8]
 [8]
 [8]
 [1]
 [3]
 [3]]


In [18]:
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
arr2 = np.random.randint(1,20,size=(5,5))
print(arr2)
flat = arr2.flatten()
print(flat)
print(flat.reshape(5,5))

[[13  3 14  9  7]
 [19 17 19 10  3]
 [19  4 18 17  4]
 [17  5 19 10 18]
 [15 11  5  6  7]]
[13  3 14  9  7 19 17 19 10  3 19  4 18 17  4 17  5 19 10 18 15 11  5  6
  7]
[[13  3 14  9  7]
 [19 17 19 10  3]
 [19  4 18 17  4]
 [17  5 19 10 18]
 [15 11  5  6  7]]


In [4]:
### Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
arr = np.random.randint(1,20,size=(5,5))
print("Original Array:")
print(arr)

corners = arr[[0,0,-1,-1],[0,-1,0,-1]]
print("Corners Element")
print(corners)

Original Array:
[[ 8  4  7  7 14]
 [19 17 19  3  3]
 [13  3 17  3  4]
 [ 1 19 19 13 15]
 [ 7 10  6  3 11]]
Corners Element
[ 8 14  7 11]


In [5]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.
arr = np.random.randint(1,20,size=(4,4))
print(arr)
arr[arr>10] = 10
print(arr)

[[ 3 16 18 13]
 [19  5  2  7]
 [ 1  6  9  9]
 [13  2  2  4]]
[[ 3 10 10 10]
 [10  5  2  7]
 [ 1  6  9  9]
 [10  2  2  4]]


In [11]:
### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
dtypes = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([
    ('Anushka',25,55.5),
    ('Rajat',28,68.0),\
    ('Sonia',22,42.0),
    ('Salabh',24,60.0)
],dtypes)

print(data)
sorted_data = np.sort(data,order = 'age')
print(sorted_data)

[('Anushka', 25, 55.5) ('Rajat', 28, 68. ) ('Sonia', 22, 42. )
 ('Salabh', 24, 60. )]
[('Sonia', 22, 42. ) ('Salabh', 24, 60. ) ('Anushka', 25, 55.5)
 ('Rajat', 28, 68. )]


In [15]:
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
dtypes = [('x','i4'),('y','i4')]
points = np.array([
    (1,2),
    (3,4),
    (6,8),
    (2,1)
],dtypes)

distance = np.sqrt(points['x']**2+points['y']**2)
print(distance)

[ 2.23606798  5.         10.          2.23606798]


In [17]:
### Assignment 10: Masked Arrays

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
arr = np.random.randint(1,20,size=(4,4))
masked_arr = np.ma.masked_greater(arr,10)
print(masked_arr)

sum_unmasked = masked_arr.sum()
print(sum_unmasked)

[[10 7 -- 3]
 [-- -- 8 1]
 [-- -- 10 1]
 [-- 1 5 --]]
46


In [21]:
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
arr = np.random.randint(1,10,size=(3,3))
print("Original Array")
print(arr)

masked_arr = np.ma.array(arr,mask = np.eye(3,dtype=bool))
print("Maked_Array")
print(masked_arr)

mean_val = masked_arr.mean()

filled_val = masked_arr.filled(mean_val)
print(filled_val)

Original Array
[[9 8 9]
 [6 3 8]
 [9 2 9]]
Maked_Array
[[-- 8 9]
 [6 -- 8]
 [9 2 --]]
[[7 8 9]
 [6 7 8]
 [9 2 7]]
